#!/user/bin/python

### This script takes in an Orthogroups.GeneCount.tsv file generated by OrthoFinder
### and creates a file to be input into CAFE to determine the number of expanded/contracted/rapidly evolving gene familes
### Output includes ONLY orthogroups that meet a minimum threshold/presence criteria across all taxa
    ### NOTE: CAFE also requires as a species tree as input (also output from orthofinder)
        # Species names in the tree must be identical to what is output from this script (e.g., no white spaces or special characters)
        # "1"s must be removed from nodes
        # branch lengths must be scaled by multiplying them by 100 (e.g., a branch length of 0.005 is now 0.5), as CAFE cannnot accept small branch lengths

#BEFORE RUNNING: edit names of input and output files and adjust THRESHOLD/N value (e.g., removes invariant orthogroups and those with a delta < N)
input_file = "input_file_name"
output_file = "output_file_name"

#Write header to output file:
with open(output_file, "w") as outfile:
    #Header includes species names in order without white-spaces or special characters.
    outfile.write("ID\tdescription\tNlepida\tPattwateri\tPcrinitus\tPeremicus\tPleucopus\tPmaniculatus\tPnasatus\tPpolionotus\tShispidus\tMochrogaster\tMmusculus\n")

#Identify orthogroups with large variation among species (e.g., delta = max-min)
with open(input_file, "r") as infile:
    lines = infile.readlines()[1:]
    for line in lines:
        line_min = 5000
        line_max = 0
        fields = line.split()[0:]
        not_total = line.split()[0:-1] #exclude the total column to calculate the delta
        #print(fields)
        #print(not_total)
        values = not_total[1:]
        for value in values:
            if int(value) < line_min:
                line_min = int(value)
            if int(value) > line_max:
                line_max = int(value)
        #print(line_min, line_max)
        delta = line_max - line_min
        #print(delta)
        
        #Write out any lines that meet this threshold: 
        if delta < 15 and delta != 0:                         ### ADJUST THRESHOLD AS DESIRED - removes invariant orthogroups and those with a delta < N
            with open(output_file, "a") as outfile:
                outfile.write(fields[0] + '\t' + '\t'.join(not_total) + '\n')
    
